matrix:
  include:
    - os: osx
      osx_image: xcode9.4
      language: node_js
      node_js: "12"
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

    - os: linux
      services: docker
      language: generic

git:
  depth: false

cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
    - secure: eVVluxkZaqvpciWWIOUCjqeQGrm5EVFxhnjDpXCcbzisQH2o65ZP2ccHtUeX4guC2IyUB6HZKTSCiJPk4vvIFGbSL72+fu+USlDRlqpB351e7CM/qsN/ODERQQ317f/GHACiSaBzn6jBzmRMYMAoQXSxE06BCvTCOFVuPcQQG++epsr4yf0q67ox/dBmIiWnT8xZDWMMawjZf583rZfGTseqgZjz+9a/74hvhqElbK0gn4hQ7PL5sftSBVRiKdwC0ygkPfg2Mfe++XQ4h+mE8UO/3xdp1UPR1ziUhpLQ1fr+tPLl7VkcPDi5LdUS2rANsKvprLtKAaOslv7pntPAy04LVRARfCruwzWHlWlkH6SPdvgI0rbduPQ1Q4nTyTp3Mwwxxt1aZjbCQw5/uZcdhRXx/UpfMCfZW9J3VkM9EXs8HUY6gQCRWkO8U+uI+VMUScEtxq2DVe1vih2YjppmuPKspkqQ1ZFnPyLerFc/sAEnNgokzZE3FCEtNdGFxB9mCSa4otyJxCpHRQ/G2cl5wrpqt5WYFKMJi9Qyj7XSe95qdcpVi7U3392w+NobSJppJJDldj6juGVtJnc38+Mb59nPb141TYUxcaQKGy6DB+qS+HszrtDyVuGzgm0YsY82V5SRwht/6SZTOUzkubrJTyvd0c2d3NFMdZg4OW2Gaxg=

before_install:
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16
      openssl aes-256-cbc -K $encrypted_525ecc25ac52_key -iv $encrypted_525ecc25ac52_iv -in dist/deploy_key.enc -out /tmp/deploy_key -d
      chmod 600 /tmp/deploy_key
    fi

before_script:
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      export DISPLAY=:99.0
      sh -e /etc/init.d/xvfb start &
      sleep 3
    fi
  - |
    if [ "$TRAVIS_REPO_SLUG" == "Doccrazy/stash-electron" ] && [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      export DEPLOY_RELEASE=true
    elif [ "$TRAVIS_REPO_SLUG" == "Doccrazy/stash-electron" ] && [ -n "$TRAVIS_TAG" ]; then
      export DEPLOY_RELEASE=true
    fi

script:
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      docker run --rm \
        $(env | \
          grep -Eo '^[^\s=]*(DEBUG|NODE_|ELECTRON_|YARN_|NPM_|CI|CIRCLE|TRAVIS|APPVEYOR_|CSC_|_TOKEN|_KEY|AWS_|STRIP|BUILD_|DISPLAY|DEPLOY)[^\s=]*' | \
          sed '/^$/d;s/^/-e /' | \
          paste -sd ' ' \
        ) \
        -v ${PWD}:/project \
        -v ~/.cache/electron:/root/.cache/electron \
        -v ~/.cache/electron-builder:/root/.cache/electron-builder \
        -v /tmp/.X11-unix:/tmp/.X11-unix \
        electronuserland/builder:wine-01.19 \
        /bin/bash -c 'export NODE_VERSION=12.13.0 && curl -L https://nodejs.org/dist/v$NODE_VERSION/node-v$NODE_VERSION-linux-x64.tar.gz | tar xz -C /usr/local --strip-components=1 && npm config ls && ls -al /project/ && ls -al /root/ && ls l /usr/local/bin/ |grep npm && ls -l /usr/local/lib/node_modules/npm/ && npm install && npm test && DISPLAY= npm run package linux win'
    else
      npm run package mac
    fi

after_success:
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ] && [ -n "$DEPLOY_RELEASE" ] && [ -z "$DEB_SKIP_PUBLISH" ]; then
      bash dist/arch/update-aur.sh
      bash dist/bintray-cleanup.sh
    fi

before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine
