plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - ./internals/plugins/native-build-env.js

yarnPath: .yarn/releases/yarn-berry.js
packageExtensions:
  "debug@^4.0.0":
    dependencies:
      supports-color: "^7.0.0"
  "react-dnd@*":
    dependencies:
      "@react-dnd/invariant": "2.0.0"
  "electron-builder@*":
    dependencies:
      "electron-publish": "^22.9.1"
  "app-builder-lib@*":
    peerDependencies:
      "dmg-builder": "*"
  "autodll-webpack-plugin@*":
    peerDependencies:
      webpack: "^5.0.0"
  "@pmmmwh/react-refresh-webpack-plugin@*":
    peerDependencies:
      webpack-dev-server: "^4.0.0-beta.0"
