compressionLevel: mixed

packageExtensions:
  app-builder-lib@*:
    peerDependencies:
      dmg-builder: "*"
  debug@^4.0.0:
    dependencies:
      supports-color: ^7.0.0
  electron-builder@*:
    dependencies:
      electron-publish: ^23.0.6
  react-dnd@*:
    dependencies:
      "@react-dnd/invariant": 2.0.0

plugins:
  - ./internals/plugins/native-build-env.js

yarnPath: .yarn/releases/yarn-4.0.2.cjs
