cacheKeyOverride: 7

packageExtensions:
  app-builder-lib@*:
    peerDependencies:
      dmg-builder: "*"
  debug@^4.0.0:
    dependencies:
      supports-color: ^7.0.0
  electron-builder@*:
    dependencies:
      electron-publish: ^23.0.6
  react-dnd@*:
    dependencies:
      "@react-dnd/invariant": 2.0.0

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - ./internals/plugins/native-build-env.js

yarnPath: .yarn/releases/yarn-3.1.1.cjs
