name: Build/release

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    env:
      ELECTRON_CACHE: ${{ github.workspace }}/.cache/electron
      ELECTRON_BUILDER_CACHE: ${{ github.workspace }}/.cache/electron-builder
      DEPLOY_RELEASE: ${{ github.repository == 'Doccrazy/stash-electron' && (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/v')) }}

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: Cache Electron-Builder
        uses: actions/cache@v2
        with:
          path: |
            ${{ github.workspace }}/.cache/electron
            ${{ github.workspace }}/.cache/electron-builder
          key: ${{ runner.os }}-electron-builder-cache-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
          restore-keys: |
            ${{ runner.os }}-electron-builder-cache-

      - name: Install dependencies
        run: yarn install

      - name: Build/release Electron app
        run: yarn package
        env:
          GH_TOKEN: ${{ github.ref == 'refs/heads/master' && secrets.RELEASE_REPO_TOKEN || secrets.github_token }}
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
        
      - name: Update AUR package
        run: bash dist/arch/update-aur.sh
        if: ${{ env.DEPLOY_RELEASE == 'true' && runner.os == 'Linux' }}
        env:
          SSHPASS: ${{ secrets.DEPLOY_KEY_PASSPHRASE }}

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ runner.os }} Release Build
          path: |
            release/*.*
          retention-days: 7

      - name: Delete older releases
        id: delete-older-releases
        if: ${{ github.repository == 'Doccrazy/stash-electron' && github.ref == 'refs/heads/master' && runner.os == 'Linux' }}
        uses: dev-drprasad/delete-older-releases@v0.2.0
        with:
          repo: Doccrazy/stash-electron-snapshots
          keep_latest: 10
          delete_tags: true  
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_REPO_TOKEN }}
